from django.db import models

# Create your models here.
class PatientInsurance(models.Model):
    #insid = models.IntegerField(default=0)
    user_name = models.CharField(max_length=20, default='larryxu')
    first_name = models.CharField(max_length=20, default='Jane')
    last_name = models.CharField(max_length=20, default='Doe')
    initial = models.CharField(max_length=20, default='x')
    relationToPatient = models.CharField(max_length=20, default='parent to children')
    dob = models.CharField(max_length=30, default='now')
    socSec = models.IntegerField(default=0)
    address = models.CharField(max_length=50, default='main st')
    city = models.CharField(max_length=20, default='columbus')
    state = models.CharField(max_length=20, default='OH')
    zip = models.CharField(max_length=20, default='43201')
    homephone = models.CharField(max_length=20, default='6144445566')
    cellphone = models.CharField(max_length=20, default='6144445566')
    email = models.CharField(max_length=20, default='example@emamil.com')
    employerName = models.CharField(max_length=20, default='John')
    employerOccupation = models.CharField(max_length=20, default='manager')
    employerBusAddr = models.CharField(max_length=20, default='main st')
    employerBusPhone = models.CharField(max_length=20, default='6144445566')
    employerBusEmail = models.CharField(max_length=20, default='example@email.com')
    insurComp = models.CharField(max_length=20, default='franklin')
    insurCompPhone = models.CharField(max_length=20, default='6144445566')
    insurContNum = models.CharField(max_length=20, default='6144445566')
    insurGroupNum = models.CharField(max_length=20, default='6144445566')
    insurSubscNum = models.CharField(max_length=20, default='6144445566')
    dependentName = models.CharField(max_length=20, default='Jane Doe')