# Generated by Django 2.2.6 on 2019-10-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientmedicalhistory', '0002_medhistoryinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medhistoryinfo',
            old_name='symptom',
            new_name='label',
        ),
        migrations.AddField(
            model_name='medhistoryinfo',
            name='med_history',
            field=models.CharField(default='symptoms', max_length=100),
        ),
    ]
